import { describe, it, expect, vi, beforeEach } from 'vitest'
import {
    filterCopilotThreads,
    formatPrDetailsText,
    fetchPrDetails,
    fetchPrIterations,
    fetchPrThreads,
    fetchPrCommits,
    type PrDetails,
    type PrThread,
    type PrIteration,
} from '../ado-api/pull-requests'
import { AdoClient } from '../ado-api/client'

const mockPr: PrDetails = {
    pullRequestId: 42,
    title: 'Add feature',
    status: 'active',
    repository: { name: 'MyRepo' },
    sourceRefName: 'refs/heads/feature/test',
    targetRefName: 'refs/heads/main',
    isDraft: false,
    mergeStatus: 'succeeded',
    description: 'Implements feature\nFixes #123',
    createdBy: { displayName: 'John Doe', uniqueName: 'john@example.com' },
    creationDate: '2024-01-15T10:00:00Z',
    reviewers: [
        { displayName: 'Jane Smith', vote: 10, isRequired: true },
        { displayName: 'Bob Jones', vote: 0, isRequired: false },
    ],
}

const threads: PrThread[] = [
    {
        id: 101,
        status: 'active',
        threadContext: { filePath: '/src/index.ts', rightFileStart: { line: 10 } },
        comments: [{
            id: 1,
            content: 'Fix this. [Generated by GitHub Copilot]',
            commentType: 'text',
            author: { displayName: 'Build Service (org)', uniqueName: 'build@system' },
            publishedDate: '2024-01-15T12:00:00Z',
        }],
    },
    {
        id: 102,
        status: 'active',
        comments: [
            {
                id: 1,
                content: 'Security issue. [Generated by Claude Code]',
                commentType: 'text',
                author: { displayName: 'Bot User', uniqueName: 'bot@local' },
                publishedDate: '2024-01-15T12:30:00Z',
            },
            {
                id: 2,
                content: 'Will fix.',
                commentType: 'text',
                author: { displayName: 'John Doe', uniqueName: 'john@example.com' },
                publishedDate: '2024-01-15T13:00:00Z',
            },
        ],
    },
    {
        id: 103,
        status: 'fixed',
        comments: [{
            id: 1,
            content: 'Regular review comment',
            commentType: 'text',
            author: { displayName: 'John Doe', uniqueName: 'john@example.com' },
            publishedDate: '2024-01-15T14:00:00Z',
        }],
    },
    {
        id: 104,
        status: 'active',
        comments: [{
            id: 1,
            content: 'System notification',
            commentType: 'system',
            author: { displayName: 'System', uniqueName: 'system@devops' },
            publishedDate: '2024-01-15T14:00:00Z',
        }],
    },
]

const iterations: PrIteration[] = [{
    id: 1,
    createdDate: '2024-01-15T10:00:00Z',
    updatedDate: '2024-01-15T11:00:00Z',
    sourceRefCommit: { commitId: 'abc123' },
    targetRefCommit: { commitId: 'def456' },
}]

describe('filterCopilotThreads', () => {
    it('includes thread authored by Build Service', () => {
        const result = filterCopilotThreads(threads)
        expect(result.find(t => t.threadId === 101)).toBeDefined()
    })

    it('includes thread with [Generated by Claude Code] attribution', () => {
        const result = filterCopilotThreads(threads)
        expect(result.find(t => t.threadId === 102)).toBeDefined()
    })

    it('excludes regular user threads', () => {
        const result = filterCopilotThreads(threads)
        expect(result.find(t => t.threadId === 103)).toBeUndefined()
    })

    it('excludes system comment threads', () => {
        const result = filterCopilotThreads(threads)
        expect(result.find(t => t.threadId === 104)).toBeUndefined()
    })

    it('maps filePath and startLine from threadContext', () => {
        const result = filterCopilotThreads(threads)
        const t = result.find(t => t.threadId === 101)!
        expect(t.filePath).toBe('/src/index.ts')
        expect(t.startLine).toBe(10)
    })

    it('sets filePath null when threadContext is missing', () => {
        const result = filterCopilotThreads(threads)
        const t = result.find(t => t.threadId === 102)!
        expect(t.filePath).toBeNull()
    })

    it('includes replies from subsequent comments', () => {
        const result = filterCopilotThreads(threads)
        const t = result.find(t => t.threadId === 102)!
        expect(t.replies).toHaveLength(1)
        expect(t.replies[0].content).toBe('Will fix.')
    })

    it('returns empty array for empty input', () => {
        expect(filterCopilotThreads([])).toEqual([])
    })
})

describe('formatPrDetailsText', () => {
    it('includes PR title and ID', () => {
        const text = formatPrDetailsText(mockPr, threads, iterations, [], 'https://dev.azure.com/org')
        expect(text).toContain('Add feature')
        expect(text).toContain('#42')
    })

    it('strips refs/heads/ prefix from branch names', () => {
        const text = formatPrDetailsText(mockPr, threads, iterations, [], 'https://dev.azure.com/org')
        expect(text).toContain('feature/test')
        expect(text).toContain('main')
        expect(text).not.toContain('refs/heads/')
    })

    it('shows reviewer votes', () => {
        const text = formatPrDetailsText(mockPr, threads, iterations, [], 'https://dev.azure.com/org')
        expect(text).toContain('Approved')
        expect(text).toContain('No vote')
    })

    it('shows copilot threads JSON block when present', () => {
        const copilotThreads = filterCopilotThreads(threads)
        const text = formatPrDetailsText(mockPr, threads, iterations, copilotThreads, 'https://dev.azure.com/org')
        expect(text).toContain('COPILOT COMMENT THREADS (JSON)')
    })

    it('omits copilot JSON block when no copilot threads', () => {
        const text = formatPrDetailsText(mockPr, threads, iterations, [], 'https://dev.azure.com/org')
        expect(text).not.toContain('COPILOT COMMENT THREADS')
    })

    it('shows no description message when description is empty', () => {
        const pr = { ...mockPr, description: '' }
        const text = formatPrDetailsText(pr, [], [], [], 'https://dev.azure.com/org')
        expect(text).toContain('No description provided')
    })

    it('shows no reviewers message when reviewers list is empty', () => {
        const pr = { ...mockPr, reviewers: [] }
        const text = formatPrDetailsText(pr, [], [], [], 'https://dev.azure.com/org')
        expect(text).toContain('No reviewers assigned')
    })

    it('includes closed by info when present', () => {
        const pr = { ...mockPr, closedBy: { displayName: 'Alice' }, closedDate: '2024-01-16T00:00:00Z' }
        const text = formatPrDetailsText(pr, [], [], [], 'https://dev.azure.com/org')
        expect(text).toContain('Alice')
    })
})

describe('fetchPr* API functions', () => {
    let client: AdoClient

    beforeEach(() => {
        client = new AdoClient({ collectionUri: 'https://dev.azure.com/org', project: 'P', token: 'tok', authType: 'Bearer' })
        vi.spyOn(client, 'get').mockResolvedValue({} as any)
    })

    it('fetchPrDetails calls get with correct PR path', async () => {
        vi.spyOn(client, 'get').mockResolvedValue(mockPr)
        const result = await fetchPrDetails(client, 'MyRepo', 42)
        expect(result).toEqual(mockPr)
    })

    it('fetchPrIterations returns value array', async () => {
        vi.spyOn(client, 'get').mockResolvedValue({ value: iterations })
        const result = await fetchPrIterations(client, 'MyRepo', 42)
        expect(result).toEqual(iterations)
    })

    it('fetchPrIterations returns empty array when value is missing', async () => {
        vi.spyOn(client, 'get').mockResolvedValue({})
        const result = await fetchPrIterations(client, 'MyRepo', 42)
        expect(result).toEqual([])
    })

    it('fetchPrThreads returns value array', async () => {
        vi.spyOn(client, 'get').mockResolvedValue({ value: threads })
        const result = await fetchPrThreads(client, 'MyRepo', 42)
        expect(result).toEqual(threads)
    })

    it('fetchPrCommits returns value array', async () => {
        const commits = [{ commitId: 'abc', comment: 'feat', author: { name: 'John', date: '' } }]
        vi.spyOn(client, 'get').mockResolvedValue({ value: commits })
        const result = await fetchPrCommits(client, 'MyRepo', 42)
        expect(result).toEqual(commits)
    })
})
