import { EventEmitter } from 'node:events';
import type { ChildProcess } from 'node:child_process';
import type { PrDetails, PrIteration, PrThread, PrCommit } from '../ado-api/pull-requests';
import type { ChangeEntry } from '../context/diff-fetcher';

// --- Constants ---
export const MOCK_GITHUB_PAT = 'ghp_mockToken123';
export const MOCK_ADO_PAT = 'ado_mock_pat_456';
export const MOCK_SYSTEM_TOKEN = 'sys_token_789';
export const MOCK_COLLECTION_URI = 'https://dev.azure.com/myorg';
export const MOCK_PROJECT = 'MyProject';
export const MOCK_REPO = 'MyRepo';
export const MOCK_PR_ID = '42';
export const MOCK_PROMPT_TEMPLATE = 'Review code:\n%CUSTOMPROMPT%\nFollow best practices.';
export const MOCK_WORKING_DIR = '/tmp/agent-work';

// --- Mock PR Data ---
export const mockPrDetails: PrDetails = {
    pullRequestId: 42,
    title: 'Add new feature',
    status: 'active',
    repository: { name: 'MyRepo' },
    sourceRefName: 'refs/heads/feature/test',
    targetRefName: 'refs/heads/main',
    isDraft: false,
    mergeStatus: 'succeeded',
    description: 'Implements the new feature\nFixes #123',
    createdBy: { displayName: 'John Doe', uniqueName: 'john@example.com' },
    creationDate: '2024-01-15T10:00:00Z',
    reviewers: [
        { displayName: 'Jane Smith', vote: 10, isRequired: true },
        { displayName: 'Bob Jones', vote: 0, isRequired: false },
    ],
};

export const mockIterations: PrIteration[] = [
    {
        id: 1,
        createdDate: '2024-01-15T10:00:00Z',
        updatedDate: '2024-01-15T11:00:00Z',
        sourceRefCommit: { commitId: 'abc123def456789abc' },
        targetRefCommit: { commitId: 'def456abc123789def' },
    },
];

export const mockThreads: PrThread[] = [
    {
        id: 101,
        status: 'active',
        threadContext: { filePath: '/src/index.ts', rightFileStart: { line: 10 } },
        comments: [{
            id: 1,
            content: 'Consider refactoring this. [Generated by GitHub Copilot]',
            commentType: 'text',
            author: { displayName: 'Build Service (myorg)', uniqueName: 'build@system.local' },
            publishedDate: '2024-01-15T12:00:00Z',
        }],
    },
    {
        id: 102,
        status: 'active',
        comments: [
            {
                id: 1,
                content: 'Security issue here. [Generated by Claude Code]',
                commentType: 'text',
                author: { displayName: 'Bot User', uniqueName: 'bot@local' },
                publishedDate: '2024-01-15T12:30:00Z',
            },
            {
                id: 2,
                content: 'Will fix this.',
                commentType: 'text',
                author: { displayName: 'John Doe', uniqueName: 'john@example.com' },
                publishedDate: '2024-01-15T13:00:00Z',
            },
        ],
    },
    {
        id: 103,
        status: 'fixed',
        comments: [{
            id: 1,
            content: 'Regular review comment',
            commentType: 'text',
            author: { displayName: 'John Doe', uniqueName: 'john@example.com' },
            publishedDate: '2024-01-15T14:00:00Z',
        }],
    },
    {
        id: 104,
        status: 'active',
        comments: [{
            id: 1,
            content: 'System notification',
            commentType: 'system',
            author: { displayName: 'System', uniqueName: 'system@devops' },
            publishedDate: '2024-01-15T14:00:00Z',
        }],
    },
];

export const mockCommits: PrCommit[] = [
    {
        commitId: 'abc123def456789abc',
        comment: 'feat: implement new feature with full tests',
        author: { name: 'John Doe', date: '2024-01-15T09:00:00Z' },
    },
    {
        commitId: 'def789ghi012345def',
        comment: 'fix: address review feedback',
        author: { name: 'John Doe', date: '2024-01-15T11:00:00Z' },
    },
];

export const mockChangeEntries: ChangeEntry[] = [
    { changeType: 'edit', item: { path: '/src/index.ts' } },
    { changeType: 'add', item: { path: '/src/utils/helper.ts' } },
    { changeType: 'delete', item: { path: '/src/old.ts' } },
    { changeType: 'edit', item: { path: '/src/', isFolder: true } },
];

/**
 * Builds a mock ChildProcess that fires close/error events on next tick.
 */
export function makeMockChildProcess(opts: {
    exitCode?: number;
    error?: Error;
    stdout?: string;
    stderr?: string;
} = {}): ChildProcess {
    const proc = new EventEmitter();
    const stdout = new EventEmitter();
    const stderr = new EventEmitter();

    (proc as any).stdout = stdout;
    (proc as any).stderr = stderr;
    (proc as any).kill = () => true;
    (proc as any).pid = 12345;
    (proc as any).stdin = null;

    process.nextTick(() => {
        if (opts.stdout) stdout.emit('data', Buffer.from(opts.stdout));
        if (opts.stderr) stderr.emit('data', Buffer.from(opts.stderr));
        if (opts.error) {
            proc.emit('error', opts.error);
        } else {
            proc.emit('close', opts.exitCode ?? 0);
        }
    });

    return proc as unknown as ChildProcess;
}

/**
 * Builds a mock fetch Response.
 */
export function makeFetchResponse(data: unknown, status = 200): Response {
    const body = typeof data === 'string' ? data : JSON.stringify(data);
    return {
        ok: status >= 200 && status < 300,
        status,
        text: async () => body,
        headers: { get: () => null },
    } as unknown as Response;
}
